### ISSUE TITLE
Add thread id when logging

### ISSUE THREAD

**Issue by takev** [ttauri-project/ttauri#123]
When logging include the thread_id.
The thread_id should be converted to a thread name when actually logging.

**Comment by jhalakpatel** [comment]
@takev can I work on this issue?
If yes, can you elaborate on the issue here?  Do we need to pass `current_thread_id` to `tt_log` macro variants?

**Comment by takev** [comment]
I think the best location for calling `current_thread_id()` would be in the constructor of `log_message`. In the same way as the timestamp is recorded.

The timestamp is recorded in that place to make sure the emitted assembly of the TSC instruction is close to where the member variable is initialised to reduce register pressure. For the TSC instruction this is especially needed because it is serialising.

That would also mean that the _thread_id member variable should come after the _timestamp. Because initialisation order of member variables are done in-order.

I have thought of the thread_id -> thread_name requirement. I think I rather log the integer-thread-id, we already log setting the thread name, so we can figure out which thread anyway.

Maybe the thread-id and cpu-id should be printed at the end of the line, like the source line and source file are.

**Comment by jhalakpatel** [comment]
IIUC,
1. We do not need thread_id -> thread_name? If it was the case, how would we get thread name from thread_id. I do not see any helper method to do that?
2. Regarding cpu-id, should this be logged as well? Should I be using `cpu_id_x64` or `time_stamp_count.cpu_id()`?

**Comment by takev** [comment]
We do not need the thread name. There is no function for it yet. There are two ways to get that, either from the operating system, or by keeping a table when the thread name was set.

Yes the CPU-id needs to be logged as well, you would use the cpu_id from the timestamp that is being logged. There is a issue for logging the relative time between log messages, that requires us to know from which CPU it came and should therefor be logged near the relative time.
