### ISSUE TITLE
Create wrapper around std::mutex

### ISSUE THREAD

**Issue by takev** [ttauri-project/ttauri#136]
Add tt::mutex as a wrapper around std::mutex that uses the dead_lock_detector.

**Comment by PinkFlufflyLlama** [comment]
You mentioned that you changed some things with your mutex pattern - is this still a valid issue?

**Comment by takev** [comment]
Yip, this is still valid.

I still use the unfair_mutex, and I would like to have the a mutex and a recursive mutex that are simple wrappers around std::mutex and std::recursive_mutex.

It allows people or me to use a more complex mutex with the security of having dead lock checks.

**Comment by takev** [comment]
meh
