### ISSUE TITLE
Input field show error

### ISSUE THREAD

**Issue by takev** [ttauri-project/ttauri#142]
Show an error to the right side of the input field when the input field contains incorrect data.

**Comment by Zengit123** [comment]
I will offer nothing valuable in this comment, I am here to hope you can give me advice.
I want to learn C++ apart from the syntax and standard functions - something I can really use to create meaningful code and contribute to open-source + get a valuable skill. The road is long, I know. This is why I figured the best way to learn is by trying to fix GitHub issues, but I got stuck on a little problem:
This issue provides no context for me, with the knowledge I have I cannot understand how the application works with all its files. Do you reckon there is a method I can fix code without knowing how the application works, or do I have to really dive into 1 repository, try to understand all of its functionality and only then try and fix the issues.
Also, should I build the application of every repository that has an issue to find the issue, or can I figure out a way to fix it just by looking at the code?
Thank you.

**Comment by takev** [comment]
My description of this issue is really short, possible too short to mark it as "good first issue".

My idea for "good first issue" is for someone unfamiliar with the code base can pick this up easily because the issue is localised to one or very few files. For this issue only ttauri/widgets/text_field_widget.hpp needs to be modified. This is separate from the coding experience one should have to work on this issue.

Also on github an "issue" does not have to be a bug. For this issue new code needs to be written which adds a feature to the text_field_widget.

Very likely you will need to be able to build the application to be able to try and test the changes you have made. Most developers would pick one or just a few open source projects to work on, because it is a lot of work to familiarise yourself to the code base and to set your development environment to build a project.
