### ISSUE TITLE
App hangs, doesn't redraw (initially transparent) when screen DPI scaling is greater than 100%

### ISSUE THREAD

**Issue by nyanpasu64** [ttauri-project/ttauri#151]
When I build in Visual Studio in ReleaseWithDebugInfo and launch ttauri_demo.exe, I get an invisible transparent window showing nothing but a shadow (and sometimes 1-pixel opaque lines on the top and bottom).

![ttauri demo missing](https://user-images.githubusercontent.com/913957/115405303-fc06a580-a1a2-11eb-9cf1-fdce60e9f0d7.png)
![black lines](https://user-images.githubusercontent.com/913957/115405294-f9a44b80-a1a2-11eb-909d-ff53c238dc04.png)

Messages printed to stdout: [ttauri-stdout.txt](https://github.com/ttauri-project/ttauri/files/6343983/ttauri-stdout.txt)

- Visual Studio 16.9 (release), MSVC 19.28.29914
- 125% DPI scaling
- Switchable graphics, Intel(R) HD Graphics 520 and AMD Radeon (TM) R5 M330 (I think only Intel is being used)

**Comment by takev** [comment]
How about when DPI is set to 100%?

From the log it seems that the render threads keeps requesting a different size window. Although the log is incomplete for fully debugging, I guess I should add some more places for logging.

**Comment by PinkFlufflyLlama** [comment]
Very curious, I have seen it do that whenever the app has raised an
exception before anything that has rendered which in my case is when my
float16 with a logic error produces a whacky value and trips something it
shouldnt. It does make me wonder though if it is an issue with a missing
Cpu instruction so would you mind telling us your processors model and also
your graphics card model

Thanks, Caleb.

**Comment by roland-ruedenauer** [comment]
Saw the same when testing 2 days ago. Dpi scaling on the machine used is 150%.
Having a look in the debugger I found the swapchain for the window was never built as method gui_window_vulkan::build() was always left at [line 175](https://github.com/ttauri-project/ttauri/blob/8d25d08c5f0504c011441abe5e332d2f9d975740/src/ttauri/GUI/gui_window_vulkan.cpp#L175).
Closing the application window in this state gave same crash reports as same raw VmaAllocation fields were not initialized with nullptr.

**Comment by nyanpasu64** [comment]
CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. I suspect this bug isn't caused by my CPU.

The app hangs whenever the DPI scaling factor is not 100%. It unhangs when I set it to 100% after startup, and hangs when I set it to 125% or 200% after startup. I can repeat both steps to hang and unhang the app.

> Closing the application window in this state gave same crash reports as same raw VmaAllocation fields were not initialized with nullptr.

I see the same thing when I launch the demo app in Visual Studio's debugger and close the window. I suspect this is a race condition that can occur even without the DPI bug.

**Comment by takev** [comment]
Although there is no dpi support yet, I expect it to at least open the window.
The crash on exit, I will also investigate first.

I will look into it today or tomorrow (I need to do taxes).

**Comment by takev** [comment]
Shutting down is pretty touch. One of the issues is the render thread still calling window methods while the window system is shutting down. Not so long ago I partly solved that, but I am working on a better methods of constructing and destructing subsystem.

**Comment by nyanpasu64** [comment]
spitballing since I don't have an understanding of ttauri, nor am a threading expert (but do have some experience working with threads and lock-free code)... maybe have an atomic shutdown flag or message queue, for the GUI event loop to tell the render thread to shutdown... then after the GUI thread sets it, it joins on the render thread?

**Comment by takev** [comment]
I already use jthread which allows for atomically stopping a thread. That is not enough. There is a lot involved in shutting down an application, and things need to be tear down in just the right order. I am working on it, but it will take weeks of development to get it all sorted out.

**Comment by takev** [comment]
Anyway, as for this bug, I used to use SetThreadDpiAwarenessContext(), but that is not enough you also need to use SetProcessDpiAwarenessContext().

So the application is not DPI aware yet, now it will always show at the same size. In the future I will do actual DPI awareness which should scale the window properly.
