### ISSUE TITLE
(Mostly) cannot select or delete last character in numeric text field

### ISSUE THREAD

**Issue by nyanpasu64** [ttauri-project/ttauri#153]
Latest main branch, commit 1ea30b0377ae900560b38cb611ca188c64e52d89.

- Open the demo app's preferences window.
- Click either of the sampling rate text fields. (Both have value 0.)
- Pressing Ctrl+A, nothing is selected. Pressing End, the cursor remains at the beginning. Pressing Delete does not remove the last digit.
- If you type some extra digits, then press Ctrl+A, the last character is not selected. End moves the cursor 1 digit from the end. Delete does nothing if the cursor is to the left of the last digit.
- The right arrow key and mouse selection, can still move the cursor past the last character or select it. At this point, backspace and delete work as expected.

**Comment by takev** [comment]
Thank you, for the collection of these issues.

**Comment by takev** [comment]
I wonder if there is a way to have automated test which tests the functionality of widgets.
Without it being fragile.

I have already thought of how to test the GUI of a full application, which I will be implementing. I wonder if I can somehow extend that to fully test an individual widget.
