### ISSUE TITLE
Buildable without vcpkg

### ISSUE THREAD

**Issue by takev** [ttauri-project/ttauri#165]
Make ttauri buildable with and without vcpkg.

**Comment by PinkFlufflyLlama** [comment]
I've recently been experimenting with conan which has been significantly nicer for a CLI workflow

**Comment by takev** [comment]
Does conan build with cmake?
For some reason I have in my head that conan is a build system on its own and not just a package manager.
Am I wrong?

**Comment by PinkFlufflyLlama** [comment]
conan is just a package manger. I've just put a demo for conan on gh for you https://github.com/PinkFlufflyLlama/conan-example where you can see there is a conanfile.txt that defines the package that I want to install.

Then there is my build.ps1 script that runs moves into a separate build folder and runs `conan install .. -s build_type=Debug` to install the packages and then it just runs the bog standard cmake commands.

**Comment by takev** [comment]
Interesting.
I think it is possible to get it to work with either or non of the package managers.

**Comment by PinkFlufflyLlama** [comment]
at this point what libraries does ttauri rely on from vcpkg?

**Comment by takev** [comment]
Vulkan and vulkan-memory-allocator. And ttauri itself when building the ttauri_hello_world project.

**Comment by PinkFlufflyLlama** [comment]
I'm not super hot on my cmake but I might have a stab at getting conan to work tonight

**Comment by PinkFlufflyLlama** [comment]
to add conan support I'm going to need to do some powershell magic but I think its all within my skillset so with your blessing may I work on conan support for ttauri?

**Comment by takev** [comment]
I made a separate issue for conan support for you.
The changes that I will be making on the cmake files for allowing to be build without a package manager should be small and not interfere with your conan changes.

**Comment by PinkFlufflyLlama** [comment]
Sounds good
