### ISSUE TITLE
Improve timestamping

### ISSUE THREAD

**Issue by takev** [ttauri-project/ttauri#20]
Currently I use the RDTSC to retrieve the 64 bit TSC timestamp.
Many modern motherboard will synchronize the clock between CPU sockets, but not all of them do.

Therefor we should calibrate a realtime clock on the TSC for each physical CPU. This can be done by running a thread that switches between CPU by changing the affinity mask.

We need to also switch to using RDTSCP to retrieve both the TSC and a CPU-id. The CPU-id itself is a opaque number that should accompany the TSC in a timestamp struct. Windows has the `__rdtscp()` intrinsic for retrieving both values.

In the current version the timestamp is stored as a `<chrono>` type; `cpu_counter_clock`. With this change, I think we should remove the fact that this is a `<chrono>` type completely, because it now will include an opaque cpu_id.

Maybe call the type `cpu_timestamp`, while keeping the static `now()` method interface. I think there should be two static method that retrieve the current timestamp, on that uses memory fences and another that doesn't. Possibly `now()` should be the serialising version, while the other is called `non_serialising_now()` or `fast_now()` or `quick_now()`.

The non-serialising version is for when you want to get the timestamp quickly but not necessarily super accurate, like when using `tt_log_*` functions.

**Comment by mr360** [comment]
Hi @takev, I'd like to try and tackle this issue. However, this is my first foray into opensource contributions. Is there a Discord or IRC chat that allows communication? 

The following links provide great detail regarding TSC, RDTSCP for those that were unaware. 

- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_for_real_time/7/html/reference_guide/chap-timestamping
- https://www.intel.com/content/www/us/en/embedded/training/ia-32-ia-64-benchmark-code-execution-paper.html
- https://www.ccsl.carleton.ca/~jamuir/rdtscpm1.pdf
- https://stackoverflow.com/questions/10921210/cpu-tsc-fetch-operation-especially-in-multicore-multi-processor-environment

**Comment by takev** [comment]
Hello mr360, that would be great if you could help here.

Hi yes, there is a discord at: https://discord.gg/7e8pFTsujw

I think I will work on CONTRIBUTING.md today.

**Comment by takev** [comment]
Some more information about the value inside: IA32_TSC_AUX

If we know how the CPU/Core is encoded inside this register, it may be possible to use an associative array instead of needing to search for the calibration of that CPU.

On Linux the IA32_TSC_AUX is well known https://stackoverflow.com/questions/16862620/numa-get-current-node-core.

**Comment by takev** [comment]
Have you started working on this @mr360 ?
If not, I may work on this myself combined with some other work in this area.

**Comment by takev** [comment]
Some interesting observations:
 - We no longer need to worry about leap seconds, due to hires_utc_clock and std::utc_clock including the leap seconds in the count.
 - We can ask the OS for the TSC frequency, otherwise measure it once.
 - We have a offset and drift for each CPU
 - The drift is how much to change the offset over a period of time.
 - The offset is a simple atomic 64 bit integer
 - It may be interesting to drift during the render or audio loop, since it is done often and the drift will take very little CPU time, but an extra thread would be expensive.
