### ISSUE TITLE
Expression is always true

### ISSUE THREAD

**Issue by thehlopster** [ttauri-project/ttauri#26]
https://github.com/ttauri-project/ttauri/blob/abe12d2f7174a04346386b0031092d904ccf163e/src/ttauri/math.hpp#L81-L82
https://github.com/ttauri-project/ttauri/blob/abe12d2f7174a04346386b0031092d904ccf163e/src/ttauri/math.hpp#L90
since `uint32_t` is `unsigned int` it is never lower than 0, so this checks is unnecessary and can be removed

**Comment by takev** [comment]
Both a_ and b_ should be int32_t instead.
Also I see that I use double underscore which are reserved. Thanks for telling me, I will fix this soon.
