### ISSUE TITLE
Expression is always true

### ISSUE THREAD

**Issue by thehlopster** [ttauri-project/ttauri#31]
https://github.com/ttauri-project/ttauri/blob/0513dad984c0c6501803a160b2ee4d7bd71d2673/src/ttauri/datum.hpp#L2308
https://github.com/ttauri-project/ttauri/blob/0513dad984c0c6501803a160b2ee4d7bd71d2673/src/ttauri/datum.hpp#L2317
since `uint64_t` is `unsigned long long`  it is always higher than 0, so this checks is unnecessary and can be removed

**Comment by takev** [comment]
Pretty sure lhs_ should have been int64_t instead, since we should be arithmetic shift.

I am also wondering if it should be `long long` instead of int64_t.
