### ISSUE TITLE
Create CI workflow

### ISSUE THREAD

**Issue by takev** [ttauri-project/ttauri#35]

**Comment by PinkFlufflyLlama** [comment]
@jakoch @takev Is this complete now with #52 merged in?

**Comment by takev** [comment]
It is not. I think stunt is still working on this.

**Comment by jakoch** [comment]
The changes from PR52 provide an Appveyor Integration, which builds on Windows for the triplets `x64-windows` and `x64-windows-static`. So, for now, the Windows MSVC part is complete.

But i guess, Take's plan is to get to a full build matrix, including CI runs on Linux and Mac, too, 
including runs against different compilers per platform, e.g. Linux using gcc and clang. 

The current build matrix looks like this:

Symbols used: ⚪ Build disabled. 🟢 Build succeeds. 🔴 Build fails.

|   CI / Platform  | Compiler |                       Windows                      | Linux | Mac |
|:----------------:|:--------:|:--------------------------------------------------:|:-----:|:---:|
|     AppVeyor     | MSVC2019 | x64-windows🟢  x64-windows-static 🟢                 |       |     |
|                  | ClangCL  | x64-windows⚪🔴  x64-windows-static⚪🔴                |       |     |
| Github Workflows |          |                                                    |       |     |
|      CodeQL      |          |                                                    |       |     |
