### ISSUE TITLE
Cannot build on Windows 10 x64 using MSVC or Clang

### ISSUE THREAD

**Issue by nyanpasu64** [ttauri-project/ttauri#51]
I installed the latest Visual Studio and MSVC as of yesterday-ish (v14.28).

- When I try building in Visual Studio, ttauri complains that Visual Studio bundles CMake 3.18.5 but ttauri requires 3.19.

- When I try building in VSCode CMake, CMake complains that git_version.hpp.in is missing.

- If I comment out the lines of code involving that file, I get lots of errors regarding using "auto" in argument position:
  > [build] C:\Users\nyanpasu64\code\ttauri\src\ttauri\algorithm.hpp(272,28): error C3533: a parameter cannot have a type that contains 'auto' [C:\Users\nyanpasu64\code\ttauri\build\ttauri.vcxproj]
  Context: `auto shuffle_by_index(auto first, auto last, auto indices_first, auto indices_last, auto index_op) noexcept`
    - Adding `target_compile_options(ttauri PUBLIC /std:c++latest)` does not fix this issue.

- I tried building using Clang, but found many errors when constexpr functions tried to call non-constexpr ones, or accepted/returned types with no constexpr constructors. One error I got was `class tagged_id` accepting a template argument `basic_fixed_string Tag` but erroring out due to `basic_fixed_string` needing template arguments. I gave up after that point.

**Comment by takev** [comment]
That is correct, the minimum visual studio that is needed to build ttauri is
 - MSVC 16.9 Preview 4.

This version solves some bugs with concept auto function arguments. And also adds std::jthread which is already in use by ttauri.

The clang that comes with MSVC is not very far along with the c++20 requirements needed for ttauri either.
For example clang is not able to handle basic_fixed_string yet.

**Comment by takev** [comment]
In case you are wondering why I am using such an extremely bleeding edge version of C++20.

- The library won't be stabilised for a while, so before actual products are made the compilers will have time to stabilise along side it.
- The "stable" version of visual studio often has bugs that makes it difficult for me to work with it, and it takes a really long time for bug fixes to appear. With the preview release most bugs that I report get fixed within a month or so.

**Comment by PinkFlufflyLlama** [comment]
MSVC is excelling in c++20 compatiblity followed by gcc and clang. I am working on a branch to make compiling with gcc viable so I can start working on Linux support but due to not having the same degree of support there are plenty of roadblocks to pass so I wouldn't expect anything soon.

**Comment by PinkFlufflyLlama** [comment]
@nyanpasu64 Did you get it compiling for you with MSVC 16.9 prev 4?

**Comment by nyanpasu64** [comment]
I didn't try installing MSVC preview yet, and I don't know if I'm going to try soon.

**Comment by takev** [comment]
That is okay. I think I will go and purposefully lag behind on just the C++20 features that are available in the stable version of visual studio, since this is now a public project.

**Comment by takev** [comment]
Current version of MSVC non-preview can now build ttauri's main branch.
I will try to keep this state with future development.
