### ISSUE TITLE
Fix all self assign/copy/moves.

### ISSUE THREAD

**Issue by takev** [ttauri-project/ttauri#54]
In many case there are custom copy and move assignment and constructors that are not save for assignment to self. Lets fix these.

Copy / Move Constructor
-------------------------
In normal situations self-construction does not happen without invoking undefined behaviour.
Lets add an axiom at the start of the constructor to check for self-construction.

```
tt_axiom(&other != this)
```

Copy / Move Assignment
-------------------------
In normal code it is possible for self-assignment. even the standard algorithms may use std::swap with both arguments referencing the same object.

The best way to solve this is to make sure that self-assignment simply works with the normal code, without any check. In this case we need an internal comment to mark the fact that we checked this:

```
// Self-assignment is allowed.
```

Otherwise a check is needed, which returns *this when self-assignment is happening, we mark this fact specifically 'unlikely' because it simply shouldn't really be happening:

```
tt_short_circuit_self_assignment(other);
```

The `tt_short_circuit_self_assingment()` should probably be a macro in required.hpp:
```
#define tt_short_circuit_self_assignment(other)\
  if (&(other) == this) [[unlikely]] return *this;
```

**Comment by jhalakpatel** [comment]
Hi @takev, I am interested in working on this issue. Please let me know if it is OK for me to work on it?

**Comment by takev** [comment]
Hi @jhalakpatel , I just assigned you to this issue.

**Comment by takev** [comment]
@jhalakpatel I made a small update on the issue for adding a macro for self assign check.

**Comment by jhalakpatel** [comment]
@takev Took a first stab at the issue.
For copy/move assignment operator, where self copy/move assignment was not allowed, I have just added `tt_short_circuit_self_assignment` and not put an effort to make it work as "normal" i.e. self-assignment should just work. Please let me if this is what you expected.

Also Please let me know if it adheres to the project coding standard.

**Comment by takev** [comment]
Thank you for all that work.

I will review and potentially merge the pull request in a bit.

It does seem to adhere to the coding standard.

**Comment by takev** [comment]
I am guessing there are still some classes where this is not done yet.
Otherwise I will close it again
