### ISSUE TITLE
Use inline namespaces

### ISSUE THREAD

**Issue by takev** [ttauri-project/ttauri#58]
We need to use inline namespaces to maintain ABI compatibility. On a project this size that is probably important.
We don't care much about ABI right now, since API keeps changing, but we should already start using the inline namespace in preparation.

I wonder what to name that inline namespace. `inline namespace tt_v1`?

**Comment by PinkFlufflyLlama** [comment]
Can you provide some resources for why ABI compatibility is important because all that google and Wikipedia came up with seemed rather dated.

**Comment by takev** [comment]
ABI compatibility is less problematic on windows, since most applications are bundled together with their libraries.

For Linux this is more important, since libraries are installed on the system, Linux is currently the most important reason for C++ to keep having to have ABI compatibility.

What is happening is that during compilation headers are included, which contains inline code, which much match the code that was compiled when the library was build.

Imagine a class where in version 2 the order of member-variables has changes, if the application was build with version 1 the inline methods still point to the members in the original order.

The inline-namespace can solve this partly. There would be a `v1` and a `v2` namespace, both would contain that same class, the second one with the order reversed. One-and-only-one of those two namespaces would be inlined. When a namespace is inlined all the names in that namespace becomes visible in the containing namespace, but when the name is found it still refers to the original namespace.

When happens when you compile against such a library is that although you don't explicitly program against a version, the executable that is generated does reference the version explicitly, so when the library is changed it still points to the original class.

But not only ABI, but also API stability exists, if you want to compile an old application against the library, you can include the headers with an `#define` of a specific version, or by directly using the namespace by name.

**Comment by takev** [comment]
Extra question, what happens with Doxygen with inline namespaces.

**Comment by jakoch** [comment]
> I wonder what to name that inline namespace

Maybe just the major version prefixed with `v`. It changes only, when you make incompatible API changes.

```
namespace library
{
    namespace v1
    {
        class car {
        }; 
    }

    inline namespace v2 
    {
        class car {
            // new member(s)
        }; 
    }
}
```

> what happens with Doxygen with inline namespaces.

Doxygen has partial support for `inline namespace`. The intermediate XML contains data for this item, since `Release_1_8_19`.
But i'm not sure, if output formats are ready, yet. The upstream issue is still open, ref.: https://github.com/doxygen/doxygen/issues/6741
