### ISSUE TITLE
Improve scaling and DPI strategy

### ISSUE THREAD

**Issue by jakoch** [ttauri-project/ttauri#64]
Currently ttauri will only renderer correctly at 100% scaling.
Rendering at higher scalings (e.g. 125%) will result in rendering artifacts or nothing being rendered.
The problem is reproducible by altering the scaling level in the OS system settings.

Referencing the [reddit discussion](https://www.reddit.com/r/cpp/comments/llq4z7/ttauri_modern_retainedmode_gui_library_in_c20/gnssesz/) for further details.

#### Todo

- [ ] ttauri should properly scale by the value set on the OS-level
- [ ] improve image loading accordingly

**Comment by takev** [comment]
Lets indeed look at this as well: https://github.com/NXPmicro/gtec-demo-framework/blob/master/Doc/FslSimpleUI.md
